- hosts: all
  become: true
  tasks:

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        update_cache: yes
        name: "*"
        state: latest
        autoremove: yes
        autoclean: yes
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
