---

- hosts: lxc
  become: true
  tasks:

    - name: check if promtail exist
      stat:
        path: /usr/local/bin
      register: register_name

    - name: Create directory if it doesn't already exist
      file:
        path: /usr/local/bin/
        state: directory
    
    - name: Download Promtail
      get_url:
        url: https://github.com/grafana/loki/releases/download/v2.9.4/promtail-linux-amd64.zip
        dest: /usr/local/bin/

    - name: Uznip Promtail
      ansible.builtin.unarchive:
        src: /usr/local/bin/promtail-linux-amd64.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Persmissions
      copy:
        src: /usr/local/bin/promtail-linux-amd64
        dest: /usr/local/bin/promtail-linux-amd64
        mode: a+x
        remote_src: yes

    - name: Add user
      ansible.builtin.user:
        name: promtail
        group: adm

    - name: Create Promtail service
      template: 
        src: templates/promtail.service.j2
        dest: /etc/systemd/system/promtail.service
        
    - name: Create Promtail service
      template: 
        src: templates/config-promtail.yml.j2
        dest: /usr/local/bin/config-promtail.yml
    
    - name:
      ansible.builtin.service:
        name: promtail.service
        state: started
        enabled: true

  


        


