---

- hosts: lxc
  become: true
  tasks:

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        update_cache: yes
        name: "*"
        state: latest
        autoremove: yes
        autoclean: yes
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file




    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - software-properties-common
          - wget
          - curl
    - name: Import Grafana GPG signing key [Debian/Ubuntu]
      apt_key:
        url: "https://packages.grafana.com/gpg.key"
        state: present
        validate_certs: false
      register: _add_apt_key
      until: _add_apt_key is succeeded
      retries: 5
      delay: 2

    - name: Add Grafana repository [Debian/Ubuntu]
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        update_cache: true
      register: _update_apt_cache
      until: _update_apt_cache is succeeded
      retries: 5
      delay: 2

    - name: Install promtail
      ansible.builtin.apt: 
        name: promtail
        state: present
        update_cache: yes

    - name: Move GPG key
      copy: 
        src: /etc/apt/trusted.gpg 
        dest: /etc/apt/trusted.gpg.d
        remote_src: yes

    - name: Add user
      ansible.builtin.user:
        name: promtail
        group: adm

    - name: Create Promtail service
      template: 
        src: templates/config.yml.j2
        dest: /etc/promtail/config.yml

    - name: Enable and start promtail service
      service:
        name: promtail.service
        enabled: yes
        state: restarted

