---
- name: Update web servers
  hosts: all
  remote_user: root

  tasks:
  - name: Ensure docker is at the latest version
    ansible.builtin.apt:
      name: docker
      state: latest 

  - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    