- hosts: k8s_worker
  become: true
  tasks:

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        update_cache: yes
        name: "*"
        state: latest
        autoremove: yes
        autoclean: yes

    - name: Install dependencies
      ansible.builtin.apt:
          update_cache: true
          name: 
           - nfs-common
          update_cache: true
  
    - name: Create NFS folder
      become: yes
      become_user: root
      file:
        path: /mnt/k8s_demo
        state: directory
        mode: 0755

    - name: Mount NFS
      become: true
      ansible.builtin.command: mount 192.168.1.7:/mnt/data/nfs_demo /mnt/k8s_demo

    - name: Make NFS permenant
      blockinfile:
        path: /etc/fstab
        state: present
        block: |
          192.168.1.7:/mnt/data/nfs_demo   /mnt/k8s_demo   nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0